### ISSUE TITLE
Confusing README.md, especially concerning satellite

### ISSUE THREAD

**Issue by nkadel** [powertim/deploy_awx-rpm#4]
I'm looking through your setup directions, and they're somewhat confusing. Why do they demand a "Satellite": repository, for RHEL or CentOS based servers? Even if the hosts need a local mirror repository, I'd think the repo should reflect this instead of a Satellite server. A less maintained but up-to-date repo is mentioned directly at https://awx.wiki/, with a repo file available at https://awx.wiki/repository/ansible-awx-nogpg.repo , and the full repo of obsolete versions is at https://awx.wiki/repository/ . In fact, the word "Satellite" can be replaced with "yum" and basically fix the issue.

**Comment by powertim** [comment]
Hi,

I understand your confusion but these "Satellite" repos are used with the [rhsm_repository](https://docs.ansible.com/ansible/latest/modules/rhsm_repository_module.html) and subscription manager is intended to be used with Red Hat Satellite.
In some organizations, some repositories are not enabled by default on systems and that's why there is a mandatory step to activate them with rhsm_repository module when Red Hat Satellite is present and the only trusted source.
But of course, you can modify the prerequisites roles to use directly the repos you prefer.
I still didn't find the time to add more customization with CentOS and local repos but it will be available someday.

Best,

Tim.
